// Usually, a function handles errors by passing them up to its caller.
// The `main` function can also return an `error` value.
